### PR TITLE
maintenance: upgrade to TypeScript 5, Oclif 4, node 18+

### LINKED ISSUE #448: Fully migrate to `@oclif/core` since `@oclif/command` is now deprecated
We need to fully migrate to the `@oclif/core` library to remove any usage of the now deprecated `@oclif/command` lib.

### PR DESCRIPTION
**Pull request by paulRbr**
This is basically a re-write from scratch using a newly generated package from Oclif v4 due to a too big of a jump from Oclif v1 to oclif v4.

I've then copied files from our CLI one by one making sure compilation (and features) work.

~There are still some work to be done:~ (all done :tada:)

- [x] preview cmd
- [x] diff cmd
- [x] deploy cmd
- [x] overlay cmd
- Tests
  - [x] unit
  - [x] commands (done but there's something I'm missing they don't run!)
  - [x] integration

## Notes for the reviewer

It's a big PR, sorry for that, we can do a pair-review if you feel like it :hugs:.

Also, there are a few things I had to adapt in the CLI to make this current upgrade:
- ~I couldn't get the [`open`](https://www.npmjs.com/package/open) node package to work (it was included in oclif's fancy-ux in v1 but isn't part of oclif anymore). This lead me to comment (and thus disable the `--open` flag features of the CLI)~ it works!
- I could't find a way to test a “waiting” command (the `bump preview --live` one) because the mocha test process never ends due to the command “waiting”. I tried with mocking the `stdin` ([as described here](https://github.com/oclif/test/issues/552)) but I don't think an “exit signal” character exists which I can send to `stdin` to stop the running command. This lead me to comment the related test.

Closes #448

### CODE REVIEW

**Comment by paulRbr** [comment]
> in hub, when interactive mode is selected and api filename should be removed, I have an error (only when flag --auto-create was missing, maybe a false positive)

As discussed in sync, there was a bug when selecting multiple times the same file: I've fixed the code to only present files that have not yet been selected (and thus the error should not be possible anymore)

> * node v20 is required as minimal version

Changed the minimal version in the package.json :white_check_mark:

**Comment by paulRbr** [comment]
@Polo2 could you take a second look and if happy approve the PR :pray:?

**Comment by Polo2** [comment]
> @Polo2 could you take a second look and if happy approve the PR 🙏?

Oh oh, looks like someone missed this comment 🙈 
I add it to my today todo

**Review by Polo2 — APPROVED** [review]
As discussed, this review is not the easiest one, but by testing the CLI locally I can confirm it works perfectly on my environment (mac).

Thanks for the huge work, I don't see anything blocking during the review and I trust you, so... LGTM

**Pull request merged**
